import { ProductCard } from './category.interfaces';
import sofaImage from './images/sofaImg.jpg';

export const PRODUCTS_CARDS: ProductCard[] = [
  {
    id: '1',
    name: 'Cozy sofa',
    description: 'This is the first card',
    src: sofaImage,
    price: '1500',
    discount: '10',
    brand: 'Brand 1',
    color: 'white',
  },
  {
    id: '2',
    name: 'Cozy sofa',
    description: 'This is the first card',
    src: sofaImage,
    price: '1500',
    discount: '10',
    brand: 'Brand 1',
    color: 'white',
  },
  {
    id: '3',
    name: 'Cozy sofa',
    description: 'This is the first card',
    src: sofaImage,
    price: '1500',
    discount: '10',
    brand: 'Brand 1',
    color: 'white',
  },
  {
    id: '4',
    name: 'Cozy sofa',
    description: 'This is the first card',
    src: sofaImage,
    price: '1500',
    discount: '10',
    brand: 'Brand 1',
    color: 'white',
  },
  {
    id: '5',
    name: 'Cozy sofa',
    description: 'This is the first card',
    src: sofaImage,
    price: '1500',
    discount: '10',
    brand: 'Brand 1',
    color: 'white',
  },
  {
    id: '6',
    name: 'Cozy sofa',
    description: 'This is the first card',
    src: sofaImage,
    price: '1500',
    discount: '10',
    brand: 'Brand 1',
    color: 'white',
  },
  {
    id: '7',
    name: 'Cozy sofa',
    description: 'This is the first card',
    src: sofaImage,
    price: '1500',
    discount: '10',
    brand: 'Brand 1',
    color: 'white',
  },
  {
    id: '8',
    name: 'Cozy sofa',
    description: 'This is the first card',
    src: sofaImage,
    price: '1500',
    discount: '10',
    brand: 'Brand 1',
    color: 'white',
  },
];
